name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - 'dev/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - run: bun install
      - run: bun run build
        env:
          PUBLIC_SUPABASE_URL: ''
          PUBLIC_SUPABASE_PUBLISHABLE_KEY: ''
          SUPABASE_SERVICE_ROLE_KEY: ''
